INSERT INTO `gz_anecdote_tag` VALUES (1, '学习方式', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (2, 'A 主动性与计划性', 1, 10);
INSERT INTO `gz_anecdote_tag` VALUES (3, 'B 使用材料解决问题', 1, 10);
INSERT INTO `gz_anecdote_tag` VALUES (4, 'C 回顾', 1, 10);
INSERT INTO `gz_anecdote_tag` VALUES (5, '社交情感发展', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (6, 'D 情感', 5, 10);
INSERT INTO `gz_anecdote_tag` VALUES (7, 'E 与成人建立关系', 5, 10);
INSERT INTO `gz_anecdote_tag` VALUES (8, 'F 与其他幼儿建立关系', 5, 10);
INSERT INTO `gz_anecdote_tag` VALUES (9, 'G 团体意识', 5, 10);
INSERT INTO `gz_anecdote_tag` VALUES (10, 'H 冲突解决', 5, 10);
INSERT INTO `gz_anecdote_tag` VALUES (11, '身体发育和健康', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (12, 'I 肢体运动技能', 11, 10);
INSERT INTO `gz_anecdote_tag` VALUES (13, 'J 精细运动技能', 11, 10);
INSERT INTO `gz_anecdote_tag` VALUES (14, 'K 个人护理与健康行为', 11, 10);
INSERT INTO `gz_anecdote_tag` VALUES (15, '语言，读写与交流', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (16, 'L 口语表达', 15, 10);
INSERT INTO `gz_anecdote_tag` VALUES (17, 'M 倾听和理解', 15, 10);
INSERT INTO `gz_anecdote_tag` VALUES (18, 'N 语音意识', 15, 10);
INSERT INTO `gz_anecdote_tag` VALUES (19, 'O 字母知识', 15, 10);
INSERT INTO `gz_anecdote_tag` VALUES (20, 'P 阅读', 15, 10);
INSERT INTO `gz_anecdote_tag` VALUES (21, 'Q 书籍乐趣与知识', 15, 10);
INSERT INTO `gz_anecdote_tag` VALUES (22, 'R 书写', 15, 10);
INSERT INTO `gz_anecdote_tag` VALUES (23, '数学', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (24, 'S 数字与点数', 23, 10);
INSERT INTO `gz_anecdote_tag` VALUES (25, 'T 几何学：形状与空间意识', 23, 10);
INSERT INTO `gz_anecdote_tag` VALUES (26, 'U 测量', 23, 10);
INSERT INTO `gz_anecdote_tag` VALUES (27, 'V 模式', 23, 10);
INSERT INTO `gz_anecdote_tag` VALUES (28, 'W 数据分析', 23, 10);
INSERT INTO `gz_anecdote_tag` VALUES (29, '创造性艺术', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (30, 'X 艺术', 29, 10);
INSERT INTO `gz_anecdote_tag` VALUES (31, 'Y 音乐', 29, 10);
INSERT INTO `gz_anecdote_tag` VALUES (32, 'Z 律动', 29, 10);
INSERT INTO `gz_anecdote_tag` VALUES (33, 'AA 假装游戏', 29, 10);
INSERT INTO `gz_anecdote_tag` VALUES (34, '科学与技术', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (35, 'BB 观察与分类', 34, 10);
INSERT INTO `gz_anecdote_tag` VALUES (36, 'CC 试验，预测和做出结论', 34, 10);
INSERT INTO `gz_anecdote_tag` VALUES (37, 'DD 自然和物质世界', 34, 10);
INSERT INTO `gz_anecdote_tag` VALUES (38, 'EE 工具与技术', 34, 10);
INSERT INTO `gz_anecdote_tag` VALUES (39, '社会学习', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (40, 'FF 自我与他人认知', 39, 10);
INSERT INTO `gz_anecdote_tag` VALUES (41, 'GG 地理', 39, 10);
INSERT INTO `gz_anecdote_tag` VALUES (42, 'HH 历史', 39, 10);
INSERT INTO `gz_anecdote_tag` VALUES (43, '英语学习', 0, 10);
INSERT INTO `gz_anecdote_tag` VALUES (44, 'II 英语听力与理解', 43, 10);
INSERT INTO `gz_anecdote_tag` VALUES (45, 'JJ 英语口语', 43, 10);
